services:
  telegrambotapi:
    image: telegrambotapi
    build:
      context: .
      dockerfile: TelegramBot/Dockerfile

  telegrambotapp:
    image: telegrambotapp
    build:
      context: .
      dockerfile: TelegramBotApplication/Dockerfile
  
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: telegramdb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  
